### PR TITLE
Add CSS doodle and a few links around creative coding

### PR DESCRIPTION
**Pull request by wgao19**
- Add CSS Doodle
- Add a few links around creative coding

### CODE REVIEW

**Comment by sw-yx** [comment]
oo thanks! will review individually. eventually i wanna build a demo site that combines all these.

**Comment by wgao19** [comment]
A site like a gallery?

**Comment by sw-yx** [comment]
yeah. one part for practice, one part so that if any of these links ever go dead i dont lose the info

**Comment by wgao19** [comment]
That sounds beautiful ʕ•ᴥ•ʔ
Will each exhibit be like an embedded iframe or rendering some actual usage the technique / library?

**Comment by sw-yx** [comment]
rendering actual usage. basically copy pasting all the code and making it work in context!

**Comment by wgao19** [comment]
Ohhhhh I see. This is super inspiring! I mean, the learning process led by building things. I should probably start building some meaningful stuff on my site as well 👩🏻‍🌾
Also looking forward to seeing your site live !!

**Pull request merged**
